source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Chorister_Example', :exclusive => true do
  pod "Chorister", :path => "../"
  pod 'AwesomeCache', '~> 2.0'
end

target 'Chorister_Tests', :exclusive => true do
  pod "Chorister", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
