source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Chorister_Example' do
  pod "Chorister", :path => "../"
  #pod 'AwesomeCache', '~> 2.0'
end

target 'Chorister_Tests' do
  pod "Chorister", :path => "../"
  #pod 'AwesomeCache', '~> 2.0'

  pod 'Quick'
  pod 'Nimble'
end
